main = "src/worker.tsx"
compatibility_date = "2024-05-28"

[[kv_namespaces]]
binding = "COUNTER_KV"
id = "fdsa"

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "Counter"

[[durable_objects.bindings]]
name = "SERVER_COMPONENTS"
class_name = "ServerComponents"

[[migrations]]
tag = "v1"
new_classes = ["Counter", "ServerComponents"]
